nome = input("Digite o Nome: ")
rua = input("Digite o nome da rua: ")
cep = input("Digite o CEP: ")
bairro = input("Digite o Bairro: ")
cidade = input("Digite a Cidade: ")
uf = input("Digite o Estado: ")
telefone = input("Digite um numero de Telefone: ")

while True:
    arq = open("Cadastro.txt", "a")
    arq.write("Nome: ")
    arq.write(nome)
    arq.write("\n")
    arq.write("ENDEREÇO")
    arq.write("\n")
    arq.write("   Rua: ")
    arq.write(rua)
    arq.write("\n")
    arq.write("   Cep: ")
    arq.write(cep)
    arq.write("\n")
    arq.write("   Bairro: ")
    arq.write(bairro)
    arq.write("\n")
    arq.write("   Cidade: ")
    arq.write(cidade)
    arq.write("\n")
    arq.write("   UF: ")
    arq.write(uf)
    arq.write("\n")
    arq.write("Telefone: ")
    arq.write(telefone)
    arq.write("\n")
    arq.write("------------------------------------------------------")
    arq.write("\n")
    arq.close()
    inserir = input("Deseja inserir novos dados? (sim ou nao)  ")
    if (inserir == "sim"):
        nome = input("Digite o Nome: ")
        rua = input("Digite o nome da rua: ")
        cep = input("Digite o CEP: ")
        bairro = input("Digite o Bairro: ")
        cidade = input("Digite a Cidade: ")
        uf = input("Digite o Estado: ")
        telefone = input("Digite um numero de Telefone: ")
    else:
        break


consult = input("Deseja consultar as informações já salvas? (sim ou nao)  ")

if(consult == "sim"):
    arq = open("Cadastro.txt", "r")
    lista = arq.read()
    print(lista)
    arq.close()
    input("pressione enter para fechar a aplciação")
else:
    input("pressione enter para fechar a aplciação")
